### ISSUE TITLE
The "Invert Colors" option is not persisted

### ISSUE THREAD

**Issue by feross** [sindresorhus/Plash#100]
**Describe the bug**

The "Invert Colors" option is not persisted. I set it to "Always" and then it gets unset

**To reproduce**

1. Set "Invert Colors" option to "Always"
2. Come back later and notice that it's changed back to the default "Never"

**Expected behavior**

Setting should be persisted.

**Screenshots**

<img width="268" alt="Screen Shot 2022-02-02 at 3 32 59 PM" src="https://user-images.githubusercontent.com/121766/152255437-9f05f605-8f76-43f6-aff9-f051493b9db4.png">

**Info**

 - macOS version: 12.2 (21D49)
 - Plash version: Version 2.8.3 (31)

**Additional context**

None

**Comment by sindresorhus** [comment]
Thanks for catching that. Some migration code accidentally ran each time and overwrote the setting. I fixed it now, but I'm unable to submit an update because of dumb App Store problems.

Here's a build with the fix for now: [Plash.app.zip](https://github.com/sindresorhus/Plash/files/7994853/Plash.app.zip)

**Comment by feross** [comment]
Thanks for the quick fix!

**Comment by sindresorhus** [comment]
The update is now out in the App Store: https://apps.apple.com/no/app/plash/id1494023538?mt=12
