### ISSUE TITLE
Allow the website view to go up to the top of the screen behind the Menu Bar

### ISSUE THREAD

**Issue by e-caste** [sindresorhus/Plash#107]
**Is your feature request related to a problem? Please describe.**
Yes, I'm just opening one issue instead of two since I believe having a "real" fullscreen desktop would be a better UX, but essentially my concern stems from this 1-2px high line from the wallpaper that can be seen behind the website directly below the Menu Bar:
<img width="516" alt="Screenshot 2022-06-15 at 10 17 58" src="https://user-images.githubusercontent.com/48513706/173781284-cdefb5d7-8e30-4d9b-b17d-90ac9ab68504.png">

**Describe the solution you'd like**

I don't know the specifics of macOS, so no proposed solution could be possible, but, in order of preference:
1. add a toggle that allows the website to go up to the top end of the screen behind the Menu Bar, so that it covers the part of the wallpaper that is shown in transparency behind it
2. cover at least those 2 visible pixels of the wallpaper below the Menu Bar, they're a bit annoying to look at

**Describe alternatives you've considered**

Not applicable.

**Additional context**

See above.  
Also, nice apps!

**Comment by lancoyan** [comment]
I had this problem too, I'm used to hiding the menu bar, the problem with wallpaper leaking is worse

**Comment by sindresorhus** [comment]
1. This is a good idea. I will work on this after my summer vacation.

2. It's intentional. The problem is the 1 point (2 pixels on retina) gap macOS adds. Either we show 1 point of the Plash wallpaper between the menu bar and app window or the actual wallpaper. I chose the actual wallpaper as it's less likely to be noisy. Neither are good options and it also seems like Apple has removed the gap on the newer MacBook Pro's with a taller menu bar. So I'm not really interested in changing this for older Mac's and risk annoying other users.

**Comment by sindresorhus** [comment]
Fixed in the latest update: https://apps.apple.com/no/app/plash/id1494023538?mt=12
